XTE-78, XTE-160, XTE-161  - alamsüsteemi kasutamise kohustuslikus XTE-145 - sertifikaadi DN automaatne täitmine serifikaadiprofiilist XTE-177 - logitakse .tmp failidesse XTE-182 - puuduv indeks XTE-189 - Backupfailide kontrollid ja piirangud XTE-174 - HSM reconnect XTE-92 - võtme loomisel määratakse 'label' XTE-197 - alamsüsteemi ja mitme sertifikaadi korral päringute vahendamine ebaõnnestus XTE-171 - 'No valid authentication certificate' - lisatud logimist XTE-159 - lisatud logimist

diff --git a/xtee6/packages/xroad/debian/xroad-proxy.postinst b/xtee6/packages/xroad/debian/xroad-proxy.postinst
--- a/xtee6/packages/xroad/debian/xroad-proxy.postinst
+++ b/xtee6/packages/xroad/debian/xroad-proxy.postinst
@@ -89,7 +89,12 @@ case "$1" in
 
   echo "running ${db_name} database migrations"
   cd /usr/share/xroad/db/
-  /usr/share/xroad/db/liquibase --classpath=/usr/share/xroad/jlib/proxy.jar --url="${db_url}?dialect=ee.ria.xroad.common.db.CustomPostgreSQLDialect" --changeLogFile=/usr/share/xroad/db/${db_name}-changelog.xml --password=${db_passwd} --username=${db_user}  update || die "Connection to database has failed, please check database availability and configuration ad ${db_properties} file"
+  /usr/share/xroad/db/liquibase --classpath=/usr/share/xroad/jlib/proxy.jar --url="${db_url}?dialect=ee.ria.xroad.common.db.CustomPostgreSQLDialect" --changeLogFile=/usr/share/xroad/db/${db_name}-changelog.xml --password=${db_passwd} --username=${db_user}  update || die "Connection to database has failed, please check database availability and configuration in ${db_properties} file"
+
+    if dpkg --compare-versions "$2" le-nl "6.8"
+     then
+      /usr/share/xroad/db/backup_and_remove_non-member_permissions.sh
+    fi
 
     RET=""
     db_get xroad-common/username
@@ -120,7 +125,6 @@ invoke-rc.d rsyslog restart
 invoke-rc.d nginx restart
 invoke-rc.d xroad-confclient restart
 invoke-rc.d xroad-proxy restart
-invoke-rc.d xroad-async restart
 invoke-rc.d xroad-jetty restart
 invoke-rc.d xroad-signer restart
 
