XRDDEV-571: Do not use PostgreSQL 'lo' extension
Fixes xroad-addon-messagelog does not work in AWS RDS.

diff --git a/src/packages/src/xroad/ubuntu/generic/xroad-addon-messagelog.postinst b/src/packages/src/xroad/ubuntu/generic/xroad-addon-messagelog.postinst
--- a/src/packages/src/xroad/ubuntu/generic/xroad-addon-messagelog.postinst
+++ b/src/packages/src/xroad/ubuntu/generic/xroad-addon-messagelog.postinst
@@ -1,6 +1,5 @@
 #!/bin/bash
 
-
 db_name=messagelog
 db_url=jdbc:postgresql://127.0.0.1:5432/${db_name}
 db_user=messagelog
@@ -12,22 +11,17 @@ die () {
     exit 1
 }
 
-
-
-if  [[ -f ${db_properties}  && `crudini --get ${db_properties} '' messagelog.hibernate.connection.url` != "" ]]
+if  [[ -f ${db_properties}  && $(crudini --get ${db_properties} '' messagelog.hibernate.connection.url) != "" ]]
 then
-
-   db_url=`crudini --get ${db_properties} '' messagelog.hibernate.connection.url`
-   db_user=`crudini --get ${db_properties} '' messagelog.hibernate.connection.username`
-   db_passwd=`crudini --get ${db_properties} '' messagelog.hibernate.connection.password`
-
+    db_url=$(crudini --get ${db_properties} '' messagelog.hibernate.connection.url)
+    db_user=$(crudini --get ${db_properties} '' messagelog.hibernate.connection.username)
+    db_passwd=$(crudini --get ${db_properties} '' messagelog.hibernate.connection.password)
 else
-
     echo "no db settings detected, creating local db"
 
-    if ! netstat -na | grep -q :5432
+    if ! pg_isready -h localhost -p 5432
     then
-      echo  "Is postgres running on port 5432 ?"
+      echo "Is postgres running on port 5432 ?"
       echo "Aborting installation! please fix issues and rerun with apt-get -f install"
       exit 100
     fi
@@ -39,15 +33,15 @@ else
       exit 101
     fi
 
-      if [[ `su - postgres -c "psql postgres -tAc \"SELECT 1 FROM pg_roles WHERE rolname='$db_user'\" "` == "1" ]]
+    if [[ $(su - postgres -c "psql postgres -tAc \"SELECT 1 FROM pg_roles WHERE rolname='$db_user'\" ") == "1" ]]
       then
-        echo  "$db user exists, skipping schema creation"
+        echo  "$db_user exists, skipping schema creation"
         echo "ALTER ROLE ${db_user} WITH PASSWORD '${db_passwd}';" | su - postgres -c psql postgres
       else
         echo "CREATE ROLE $db_user LOGIN PASSWORD '$db_passwd';" | su - postgres -c psql postgres
       fi
 
-      if [[ `su - postgres -c "psql postgres -tAc \"SELECT 1 FROM pg_database WHERE datname='$db_name'\""`  == "1" ]]
+      if [[ $(su - postgres -c "psql postgres -tAc \"SELECT 1 FROM pg_database WHERE datname='$db_name'\"")  == "1" ]]
       then
         echo "database $db_name exists"
       else
@@ -60,21 +54,18 @@ else
       crudini --set ${db_properties} '' messagelog.hibernate.dialect ee.ria.xroad.common.db.CustomPostgreSQLDialect
       crudini --set ${db_properties} '' messagelog.hibernate.connection.driver_class org.postgresql.Driver
       crudini --set ${db_properties} '' messagelog.hibernate.jdbc.batch_size 50
-      crudini --set ${db_properties} '' messagelog.hibernate.connection.url ${db_url}
-      crudini --set ${db_properties} '' messagelog.hibernate.connection.username  ${db_user}
-      crudini --set ${db_properties} '' messagelog.hibernate.connection.password ${db_passwd}
-
+      crudini --set ${db_properties} '' messagelog.hibernate.connection.url "${db_url}"
+      crudini --set ${db_properties} '' messagelog.hibernate.connection.username  "${db_user}"
+      crudini --set ${db_properties} '' messagelog.hibernate.connection.password "${db_passwd}"
 
 fi
-
 
 chown xroad:xroad ${db_properties}
 chmod 640 ${db_properties}
 
-su postgres -c 'psql messagelog -tAc "CREATE EXTENSION IF NOT EXISTS lo"'
 echo "running ${db_name} database migrations"
 cd /usr/share/xroad/db/
-/usr/share/xroad/db/liquibase.sh --classpath=/usr/share/xroad/jlib/proxy.jar --url="${db_url}?dialect=ee.ria.xroad.common.db.CustomPostgreSQLDialect" --changeLogFile=/usr/share/xroad/db/${db_name}-changelog.xml --password=${db_passwd} --username=${db_user}  update || die "Connection to database has failed, please check database availability and configuration in ${db_properties} file"
+/usr/share/xroad/db/liquibase.sh --classpath=/usr/share/xroad/jlib/proxy.jar --url="${db_url}?dialect=ee.ria.xroad.common.db.CustomPostgreSQLDialect" --changeLogFile=/usr/share/xroad/db/"${db_name}-changelog.xml" --password="${db_passwd}" --username="${db_user}"  update || die "Connection to database has failed, please check database availability and configuration in ${db_properties} file"
 
 service xroad-proxy restart
 
