XRDDEV-757 Add Central Server support for remote database

diff --git a/src/packages/src/xroad/ubuntu/generic/xroad-center.postinst b/src/packages/src/xroad/ubuntu/generic/xroad-center.postinst
--- a/src/packages/src/xroad/ubuntu/generic/xroad-center.postinst
+++ b/src/packages/src/xroad/ubuntu/generic/xroad-center.postinst
@@ -3,8 +3,6 @@
 #
 # see: dh_installdeb(1)
 
-#set -e
-
 # summary of how this script can be called:
 #        * <postinst> `configure' <most-recently-configured-version>
 #        * <old-postinst> `abort-upgrade' <new version>
@@ -19,37 +17,63 @@
 
 . /usr/share/debconf/confmodule
 
+local_psql() {
+  local cmd="psql -qtAU postgres $*"
+  su -l -c "$cmd" postgres
+}
 
+remote_psql() {
+  psql -h "$db_addr" -p "$db_port" -qtAU postgres "$@"
+}
+
+get_prop() {
+  crudini --get "$1" '' "$2" 2>/dev/null || echo -n "$3"
+}
 
 case "$1" in
     configure)
 
-    if ! netstat -na | grep -q :5432
-      then echo  "Is postgres running on port 5432 ?"
-       echo "Aborting installation! please fix issues and rerun with apt-get -f install"
-      exit 100
-    fi
+    db_properties=/etc/xroad/db.properties
+    root_properties=/etc/xroad.properties
 
-     if  ! su - postgres -c "psql --list -tAF ' '" | grep template1 | awk '{print $3}' | grep -q "UTF8"
-      then echo "postgreSQL is not UTF8 compatible."
-       echo "Aborting installation! please fix issues and rerun with apt-get -f install"
-       exit 101
-    fi
+    RET=
+    db_get xroad-common/database-host
+    db_host="$RET"
+    db_addr=${db_host%%:*}
+    db_port=${db_host##*:}
+    crudini --set ${db_properties} '' host ${db_addr}
+    crudini --set ${db_properties} '' port ${db_port}
 
-
-    su - postgres -c "psql postgres -tAc \"SELECT 1 FROM pg_roles WHERE rolname='centerui'\" | grep -q 1"
-    if [ $? = 1 ]
+    if  [[ -f ${root_properties} && $(get_prop ${root_properties} postgres.connection.password) != "" ]]
     then
-      su - postgres -c /usr/share/xroad/db/create_schema.sh
+        master_passwd=$(crudini --get ${root_properties} '' postgres.connection.password)
+        export PGPASSWORD=${master_passwd}
+        psql_cmd=remote_psql
     else
-      echo  "user exists, skipping postgres schema creation"
+        psql_cmd=local_psql
     fi
 
-    echo "running db migrations"
+    if  ! $psql_cmd --list -F "' '" | grep template1 | awk '{print $3}' | grep -q "UTF8"
+    then echo -e "\n\nPostgreSQL is not UTF8 compatible."
+      echo -e "Aborting installation! Please fix issues and rerun\n\n"
+      exit 101
+    fi
+
+    if [[ $($psql_cmd <<< "SELECT 1 FROM pg_roles WHERE rolname='centerui';") = "1" ]]
+    then
+      echo "User exists, skipping postgres schema creation."
+    else
+      $($psql_cmd <<< "CREATE ROLE centerui LOGIN PASSWORD 'centerui';")
+      $($psql_cmd <<< "GRANT centerui to postgres;")
+      createdb -h $db_addr -p $db_port -O centerui -U postgres -E UTF-8 centerui_production
+      $($psql_cmd -d centerui_production <<< "CREATE EXTENSION hstore;")
+    fi
+
+    echo "Running db migrations."
     /usr/share/xroad/db/migrate.sh db:migrate
     if [[ $? -ne 0 ]]
-    then 
-      echo "database migrate failed.ABORTING"
+    then
+      echo "Database migrate failed. ABORTING."
       exit 2
     fi
 
@@ -59,7 +83,6 @@ case "$1" in
 
     #add groups
     groups="xroad-security-officer xroad-system-administrator xroad-registration-officer"
-
     usergroups=" $(id -Gn "$AUSER") "
     for groupname in $groups; do
         if ! getent group "$groupname" > /dev/null; then
@@ -70,35 +93,31 @@ case "$1" in
         fi
     done
 
-    #mkdir -p  /var/lib/xroad/public
     chmod 755 /var/lib/xroad/public
     chown xroad:xroad /var/lib/xroad/public
 
     test -d /var/cache/xroad && test -w /var/cache/xroad || mkdir /var/cache/xroad ; chown xroad:xroad /var/cache/xroad
     test -d /etc/xroad/configuration-parts || mkdir /etc/xroad/configuration-parts ; chown xroad:xroad /etc/xroad/configuration-parts
 
-
     mkdir -p  /var/lib/xroad/import
     chmod 755 /var/lib/xroad/import
     chown xroad:xroad /var/lib/xroad/import
-
     ;;
 
     abort-upgrade|abort-remove|abort-deconfigure)
     ;;
-    *)
 
-        echo "postinst called with unknown argument \`$1'" >&2
-        exit 1
+    *)
+    echo "postinst called with unknown argument \`$1'" >&2
+    exit 1
     ;;
 esac
 
 # dh_installdeb will replace this with shell code automatically
 # generated by other debhelper scripts.
-
 #DEBHELPER#
-db_stop
 
+db_stop
 service rsyslog restart
 service xroad-jetty restart
 service xroad-signer restart
