XRDDEV-828 changes to messagelog installation scripts

diff --git a/src/packages/src/xroad/ubuntu/generic/xroad-addon-messagelog.postinst b/src/packages/src/xroad/ubuntu/generic/xroad-addon-messagelog.postinst
--- a/src/packages/src/xroad/ubuntu/generic/xroad-addon-messagelog.postinst
+++ b/src/packages/src/xroad/ubuntu/generic/xroad-addon-messagelog.postinst
@@ -1,11 +1,18 @@
 #!/bin/bash
 
-set -e
+set -x
 
 . /usr/share/debconf/confmodule
 
 db_name=messagelog
 db_user=messagelog
+db_conn_user="${db_user}"
+if  [[ -f ${root_properties}  && `crudini --get ${root_properties} '' postgres.connection.user.suffix` != "" ]]
+then
+    suffix=`crudini --get ${root_properties} '' postgres.connection.user.suffix`
+    db_conn_user="${db_user}${suffix}"
+fi
+
 db_passwd=$(head -c 24 /dev/urandom | base64 | tr "/+" "_-")
 db_properties=/etc/xroad/db.properties
 root_properties=/etc/xroad.properties
@@ -27,6 +34,7 @@ then
 
     db_url=`crudini --get ${db_properties} '' messagelog.hibernate.connection.url`
     db_user=`crudini --get ${db_properties} '' messagelog.hibernate.connection.username`
+    db_conn_user="${db_user}"
     db_passwd=`crudini --get ${db_properties} '' messagelog.hibernate.connection.password`
 
 else
@@ -40,27 +48,37 @@ else
 
       master_passwd=`crudini --get ${root_properties} '' postgres.connection.password`
       export PGPASSWORD=${master_passwd}
+      if [[ `crudini --get ${root_properties} '' postgres.connection.user` != "" ]]; then
+          db_master_user=`crudini --get ${root_properties} '' postgres.connection.user`
+      else
+          db_master_user=postgres
+      fi
+      db_conn_master_user="${db_master_user}"
+      if [[ `crudini --get ${root_properties} '' postgres.connection.user.suffix` != "" ]]; then
+          suffix=`crudini --get ${root_properties} '' postgres.connection.user.suffix`
+          db_conn_master_user="${db_master_user}${suffix}"
+      fi
 
-      if  ! psql -h $db_addr -p $db_port -U postgres --list -tAF ' ' | grep template1 | awk '{print $3}' | grep -q "UTF8"
+      if  ! psql -h $db_addr -p $db_port -U $db_conn_master_user --list -tAF ' ' | grep template1 | awk '{print $3}' | grep -q "UTF8"
        then echo -e "\n\npostgreSQL is not UTF8 compatible."
           echo -e "Aborting installation! please fix issues and rerun with apt-get -f install\n\n"
           exit 101
       fi
 
-      if [[ `psql -h $db_addr -p $db_port -U postgres postgres -tAc "SELECT 1 FROM pg_roles WHERE rolname='${db_user}'"` == "1" ]]
+      if [[ `psql -h $db_addr -p $db_port -U $db_conn_master_user postgres -tAc "SELECT 1 FROM pg_roles WHERE rolname='${db_user}'"` == "1" ]]
        then
           echo  "$db_user user exists, skipping role creation"
-          echo "ALTER ROLE ${db_user} WITH PASSWORD '${db_passwd}';" | psql -h $db_addr -p $db_port -U postgres postgres
+          echo "ALTER ROLE ${db_user} WITH PASSWORD '${db_passwd}';" | psql -h $db_addr -p $db_port -U $db_conn_master_user postgres
       else
-          echo "CREATE ROLE ${db_user} LOGIN PASSWORD '${db_passwd}';" | psql -h $db_addr -p $db_port -U postgres postgres
+          echo "CREATE ROLE ${db_user} LOGIN PASSWORD '${db_passwd}';" | psql -h $db_addr -p $db_port -U $db_conn_master_user postgres
       fi
 
-      if [[ `psql -h $db_addr -p $db_port -U postgres postgres -tAc "SELECT 1 FROM pg_database WHERE datname='${db_name}'"`  == "1" ]]
+      if [[ `psql -h $db_addr -p $db_port -U $db_conn_master_user postgres -tAc "SELECT 1 FROM pg_database WHERE datname='${db_name}'"`  == "1" ]]
        then
           echo "database ${db_name} exists"
       else
-          echo "GRANT ${db_user} to postgres" | psql -h $db_addr -p $db_port -U postgres postgres
-          createdb -h $db_addr -p $db_port -U postgres ${db_name} -O ${db_user} -E UTF-8
+          echo "GRANT ${db_user} to postgres" | psql -h $db_addr -p $db_port -U $db_conn_master_user postgres
+          createdb -h $db_addr -p $db_port -U $db_conn_master_user ${db_name} -O ${db_user} -E UTF-8
       fi
 
     else
@@ -107,7 +125,7 @@ chmod 640 ${db_properties}
 
 echo "running ${db_name} database migrations"
 cd /usr/share/xroad/db/
-/usr/share/xroad/db/liquibase.sh --classpath=/usr/share/xroad/jlib/proxy.jar --url="${db_url}?dialect=ee.ria.xroad.common.db.CustomPostgreSQLDialect" --changeLogFile=/usr/share/xroad/db/"${db_name}-changelog.xml" --password="${db_passwd}" --username="${db_user}"  update || die "Connection to database has failed, please check database availability and configuration in ${db_properties} file"
+/usr/share/xroad/db/liquibase.sh --classpath=/usr/share/xroad/jlib/proxy.jar --url="${db_url}?dialect=ee.ria.xroad.common.db.CustomPostgreSQLDialect" --changeLogFile=/usr/share/xroad/db/"${db_name}-changelog.xml" --password="${db_passwd}" --username="${db_conn_user}"  update || die "Connection to database has failed, please check database availability and configuration in ${db_properties} file"
 
 service xroad-proxy restart || true
 
