chore: Provision OpenBao for RHEL (#2650)
* chore: Provision OpenBao for RHEL

* chore: Common secret store init script for rhel & deb

* chore: Add remote secret store option to RHEL

diff --git a/src/packages/src/xroad/ubuntu/generic/xroad-secret-store-local.postinst b/src/packages/src/xroad/ubuntu/generic/xroad-secret-store-local.postinst
--- a/src/packages/src/xroad/ubuntu/generic/xroad-secret-store-local.postinst
+++ b/src/packages/src/xroad/ubuntu/generic/xroad-secret-store-local.postinst
@@ -4,25 +4,25 @@
 set -e
 
 if [ "$1" = "configure" ]; then
-  # Enable and start service with error handling
-  if ! deb-systemd-invoke enable openbao.service; then
-    echo "Failed to enable OpenBao service"
-    exit 1
-  fi
-
-  if ! deb-systemd-invoke start openbao.service; then
-    echo "Failed to start OpenBao service"
-    exit 1
-  fi
 
   # Only perform initialization on fresh install
   if [ -z "$2" ]; then # $2 is empty for fresh installs
-    BAO_ADDR='https://127.0.0.1:8200'
-    TMP_INIT_FILE="/tmp/bao-init.json"
-    UNSEAL_KEYS_FILE="/etc/xroad/secret-store-unseal-keys.json"
-    ROOT_TOKEN_FILE="/etc/xroad/secret-store-root-token"
+    /usr/share/xroad/scripts/secret-store-generate-tls-certificate.sh
+    # Install generated certificate to system
+    install -m 644 /opt/openbao/tls/tls.crt /usr/local/share/ca-certificates/openbao.crt
+    update-ca-certificates
 
-    # Wait for OpenBao to be ready
+    # Enable and start service with error handling
+    if ! deb-systemd-invoke enable openbao.service; then
+      echo "Failed to enable OpenBao service"
+      exit 1
+    fi
+
+    if ! deb-systemd-invoke restart openbao.service; then
+      echo "Failed to start OpenBao service"
+      exit 1
+    fi
+
     echo "Waiting for OpenBao to be ready..."
     # shellcheck disable=SC2034
     for i in $(seq 1 30); do
@@ -33,21 +33,8 @@ if [ "$1" = "configure" ]; then
     done
 
     echo "Initializing OpenBao.."
-    if ! bao operator init -key-shares=3 -key-threshold=2 -format=json >${TMP_INIT_FILE}; then
-      echo "Failed to initialize OpenBao"
-      exit 1
-    fi
-
-    jq -r '.unseal_keys_b64' ${TMP_INIT_FILE} >${UNSEAL_KEYS_FILE}
-    jq -r '.root_token' ${TMP_INIT_FILE} >${ROOT_TOKEN_FILE}
-
-    rm -f ${TMP_INIT_FILE}
-
-    echo "Running unseal service.."
     deb-systemd-invoke enable xroad-secret-store-local.service
     deb-systemd-invoke start xroad-secret-store-local.service
-
-    /usr/share/xroad/scripts/secret-store-setup.sh
   else
     echo "Upgrade detected, skipping initialization"
   fi
