Database integrity checks before center upgrade (#1793)
* feat: database integrity checks before center upgrade

Refs: XRDDEV-2472

* fix: minor fixes

Refs: XRDDEV-2472

* fix: minor fixes

Refs: XRDDEV-2472

* fix: minor fixes

Refs: XRDDEV-2472

* docs: database integrity check errors before center upgrade

Refs: XRDDEV-2472

* fix: minor sql fix

Refs: XRDDEV-2472

* fix: minor sql fix

Refs: XRDDEV-2472

* fix: fixes from code review

Refs: XRDDEV-2472

* fix: code review fix

Refs: XRDDEV-2472

* fix: minor fix

Refs: XRDDEV-2472

diff --git a/src/packages/src/xroad/ubuntu/generic/xroad-center.preinst b/src/packages/src/xroad/ubuntu/generic/xroad-center.preinst
--- a/src/packages/src/xroad/ubuntu/generic/xroad-center.preinst
+++ b/src/packages/src/xroad/ubuntu/generic/xroad-center.preinst
@@ -4,6 +4,36 @@ if [ "$1" = "upgrade" ]; then
     echo "ERROR: Upgrade supported from #LAST_SUPPORTED_VERSION# or newer" >&2
     exit 1
   fi
+
+  # Start database integrity checks
+  source /usr/share/xroad/scripts/_read_cs_db_properties.sh
+  prepare_db_props
+
+  # Start table system_parameters unique check (this check can be remove after LAST_SUPPORTED_VERSION > 7.4.0)
+  sys_param_select="select * from (select id, key, value, created_at, updated_at, ha_node_name, count(*) over (partition by key, ha_node_name order by key, ha_node_name) as count
+      from system_parameters) as s
+where s.count > 1;"
+  sys_param_check_result=$(
+    PGDATABASE="$db_database" PGUSER="$db_user" PGPASSWORD="$db_password" psql -h "$db_host" -p "$db_port" -qtA -c \
+      "$sys_param_select"
+  )
+
+  if [ -n "$sys_param_check_result" ]; then
+    echo "ERROR: Data quality issues in the $db_database database. There are duplicate data in the table SYSTEM_PARAMETERS columns pair (KEY, HA_NODE_NAME):
+----------------------------------------------------------------------------------------------------------------------------------------------
+id|key|value|created_at|updated_at|ha_node_name|count
+$sys_param_check_result
+----------------------------------------------------------------------------------------------------------------------------------------------
+
+To see duplicated rows, run the following query in the $db_database database:
+$sys_param_select
+
+Please fix incorrect data before continuing."
+    exit 1
+  fi
+  # End table system_parameters unique check
+# End database integrity checks
+
 fi
 
 # Free potentially occupied ports when upgrading from legacy installation
