XRDDEV-828 apply Jarkko's patch

diff --git a/src/packages/src/xroad/ubuntu/generic/xroad-center.postinst b/src/packages/src/xroad/ubuntu/generic/xroad-center.postinst
--- a/src/packages/src/xroad/ubuntu/generic/xroad-center.postinst
+++ b/src/packages/src/xroad/ubuntu/generic/xroad-center.postinst
@@ -49,7 +49,6 @@ setup_database() {
     crudini --set "${db_properties}" '' port "${db_port}"
 
     local db_user=$(get_prop ${db_properties} 'username' 'centerui')
-    local db_conn_user=$db_user
     local db_schema=$(get_prop ${db_properties} 'schema' "$db_user")
     local db_password=$(get_prop ${db_properties} 'password' 'centerui')
     local db_database=$(get_prop ${db_properties} 'database' 'centerui_production')
@@ -59,48 +58,44 @@ setup_database() {
     local_psql() { su -l -c "psql -qtA -p $db_port ${*@Q}" postgres; }
     remote_psql() { psql -h "$db_addr" -p "$db_port" -qtA "$@"; }
 
+    psql_dbuser() {
+        PGDATABASE="$db_database" PGUSER="$db_user" PGPASSWORD="$db_password" remote_psql "$@"
+    }
+
+    detect_bdr()  { [[ "$(psql_dbuser -c 'select bdr.bdr_version()' 2>/dev/null)" == "1.0."* ]]; }
+
     if [[ -f ${root_properties} && $(get_prop ${root_properties} postgres.connection.password) != "" ]]; then
         local db_master_passwd=$(get_prop ${root_properties} postgres.connection.password)
         db_master_user=$(get_prop ${root_properties} postgres.connection.user 'postgres')
-        db_conn_master_user="${db_master_user}"
-        if [[ $(get_prop ${root_properties} postgres.connection.login.suffix) != "" ]]; then
-            suffix=$(get_prop ${root_properties} postgres.connection.login.suffix)
-            db_conn_master_user="${db_master_user}@${suffix}"
-            db_conn_user="${db_user}@${suffix}"
-            crudini --set "${db_properties}" '' username "${db_conn_user}"
-        fi
         function psql_master() {
-            PGPASSWORD="${db_master_passwd}" PGUSER="${db_conn_master_user}" remote_psql "$@"
+            PGDATABASE="postgres" PGPASSWORD="${db_master_passwd}" PGUSER="${db_master_user}" remote_psql "$@"
         }
     else
         function psql_master() { local_psql "$@"; }
     fi
 
-    psql_dbuser() {
-        PGDATABASE="$db_database" PGUSER="$db_conn_user" PGPASSWORD="$db_password" remote_psql "$@"
-    }
-
-    detect_bdr()  { [[ "$(psql_dbuser -c 'select bdr.bdr_version()' 2>/dev/null)" == "1.0."* ]]; }
+    local db_plain_user=${db_user%%@*}
+    local db_plain_master=${db_master_user%%@*}
 
     if PGCONNECT_TIMEOUT=5 psql_dbuser -c "\q" &>/dev/null; then
         log "Database and user exists, skipping database creation."
     else
-        psql_master -d postgres <<EOF || abort "Creating database '${db_database}' on '${db_host}' failed."
+        psql_master <<EOF || abort "Creating database '${db_database}' on '${db_host}' failed."
 CREATE DATABASE "${db_database}" ENCODING 'UTF8';
 REVOKE ALL ON DATABASE "${db_database}" FROM PUBLIC;
 DO \$\$
 BEGIN
-  CREATE ROLE "${db_user}" LOGIN PASSWORD '${db_password}';
-  GRANT "${db_user}" to "${db_master_user}";
+  CREATE ROLE "${db_plain_user}" LOGIN PASSWORD '${db_password}';
+  GRANT "${db_plain_user}" to "${db_plain_master}";
   EXCEPTION WHEN OTHERS THEN
-    RAISE NOTICE 'User $db_user already exists';
+    RAISE NOTICE 'User $db_plain_user already exists';
 END\$\$;
-GRANT CREATE,TEMPORARY,CONNECT ON DATABASE "${db_database}" TO "${db_user}";
+GRANT CREATE,TEMPORARY,CONNECT ON DATABASE "${db_database}" TO "${db_plain_user}";
 \c "${db_database}"
 CREATE EXTENSION hstore;
-CREATE SCHEMA "${db_schema}" AUTHORIZATION "${db_user}";
+CREATE SCHEMA "${db_schema}" AUTHORIZATION "${db_plain_user}";
 REVOKE ALL ON SCHEMA public FROM PUBLIC;
-GRANT USAGE ON SCHEMA public to "${db_user}";
+GRANT USAGE ON SCHEMA public to "${db_plain_user}";
 EOF
     fi
 
@@ -109,10 +104,10 @@ EOF
         if ! detect_bdr; then
             psql_master --single-transaction -d "$db_database" <<EOF || abort "Renaming public schema to '$db_schema' failed."
 ALTER SCHEMA public RENAME TO "${db_schema}";
-ALTER SCHEMA "${db_schema}" OWNER TO "${db_user}";
+ALTER SCHEMA "${db_schema}" OWNER TO "${db_plain_user}";
 REVOKE ALL ON SCHEMA "${db_schema}" FROM PUBLIC;
 CREATE SCHEMA public;
-GRANT USAGE ON SCHEMA public TO "${db_user}";
+GRANT USAGE ON SCHEMA public TO "${db_plain_user}";
 ALTER EXTENSION hstore SET SCHEMA public;
 EOF
         else
