XRDDEV-547 Database connection is configured during install process

diff --git a/src/packages/src/xroad/ubuntu/generic/xroad-opmonitor.postinst b/src/packages/src/xroad/ubuntu/generic/xroad-opmonitor.postinst
--- a/src/packages/src/xroad/ubuntu/generic/xroad-opmonitor.postinst
+++ b/src/packages/src/xroad/ubuntu/generic/xroad-opmonitor.postinst
@@ -2,11 +2,12 @@
 
 set -e
 
+. /usr/share/debconf/confmodule
+
 chown xroad:xroad /etc/xroad/backup.d/??_xroad-opmonitor
 chmod 0440 /etc/xroad/backup.d/??_xroad-opmonitor
 
 db_name=op-monitor
-db_url=jdbc:postgresql://127.0.0.1:5432/${db_name}
 db_user=opmonitor
 db_passwd=$(head -c 24 /dev/urandom | base64 | tr "/+" "_-")
 
@@ -14,6 +15,13 @@ db_admin=opmonitor_admin
 db_admin_passwd=$(head -c 24 /dev/urandom | base64 | tr "/+" "_-")
 
 db_properties=/etc/xroad/db.properties
+
+RET=
+db_get xroad-common/database-host
+db_host="$RET"
+db_url=jdbc:postgresql://${db_host}/${db_name}
+db_addr=${db_host%%:*}
+db_port=${db_host##*:}
 
 die () {
     echo >&2 "$@"
@@ -29,44 +37,92 @@ then
 
 else
 
-    echo "no db settings detected, creating local db"
+    echo "no db settings detected, creating db"
 
-    if ! pg_isready -q -t 10 -p 5432
-    then
-      echo "Is postgres running on port 5432 ?"
-      echo "Aborting installation! please fix issues and rerun with apt-get -f install"
-      exit 100
-    fi
+    # If the database host is not local, connect with master username and password
+    if [[ "${db_host}" == "localhost"* || "${db_host}" == "127.0.0.1"* ]]; then
 
-    if ! su - postgres -c "psql --list -tAF ' '" | grep template1 | awk '{print $3}' | grep -q "UTF8"
-    then
-      echo "postgreSQL is not UTF8 compatible."
-      echo "Aborting installation! please fix issues and rerun with apt-get -f install"
-      exit 101
-    fi
+      if ! su - postgres -c "psql --list -tAF ' '" | grep template1 | awk '{print $3}' | grep -q "UTF8"
+      then
+          echo "postgreSQL is not UTF8 compatible."
+          echo "Aborting installation! please fix issues and rerun with apt-get -f install"
+          exit 101
+      fi
 
-    if [[ `su - postgres -c "psql postgres -tAc \"SELECT 1 FROM pg_roles WHERE rolname='$db_admin'\" "` != "1" ]]
-    then
-      echo "CREATE ROLE $db_admin LOGIN PASSWORD '${db_admin_passwd}';" | su - postgres -c psql postgres
-    fi
+      if [[ `su - postgres -c "psql postgres -tAc \"SELECT 1 FROM pg_roles WHERE rolname='$db_admin'\" "` != "1" ]]
+      then
+          echo "CREATE ROLE $db_admin LOGIN PASSWORD '${db_admin_passwd}';" | su - postgres -c psql postgres
+      fi
 
-    if [[ `su - postgres -c "psql postgres -tAc \"SELECT 1 FROM pg_roles WHERE rolname='$db_user'\" "` == "1" ]]
-    then
-      echo "$db_user exists, skipping role creation"
-      echo "ALTER ROLE ${db_user} WITH PASSWORD '${db_passwd}';" | su - postgres -c psql postgres
+      if [[ `su - postgres -c "psql postgres -tAc \"SELECT 1 FROM pg_roles WHERE rolname='$db_user'\" "` == "1" ]]
+      then
+          echo "$db_user exists, skipping role creation"
+          echo "ALTER ROLE ${db_user} WITH PASSWORD '${db_passwd}';" | su - postgres -c psql postgres
+      else
+          echo "CREATE ROLE $db_user LOGIN PASSWORD '${db_passwd}';" | su - postgres -c psql postgres
+      fi
+
+      if [[ `su - postgres -c "psql postgres -tAc \"SELECT 1 FROM pg_database WHERE datname='$db_name'\""`  == "1" ]]
+      then
+          echo "database $db_name exists"
+      else
+          su - postgres -c "createdb $db_name -O $db_admin -E UTF-8"
+      fi
+
+      echo "ALTER ROLE ${db_admin} WITH PASSWORD '${db_admin_passwd}';" | su - postgres -c psql postgres
+
+      echo "grant usage on schema public to ${db_user};" | su - postgres -c psql postgres
+      echo "grant select, insert, update, delete on all tables in schema public to ${db_user};" | su - postgres -c psql postgres
+      echo "grant usage, select, update on all sequences in schema public to ${db_user};" | su - postgres -c psql postgres
+      echo "grant execute on all functions in schema public to ${db_user};" | su - postgres -c psql postgres
+
     else
-      echo "CREATE ROLE $db_user LOGIN PASSWORD '${db_passwd}';" | su - postgres -c psql postgres
-    fi
 
-    if [[ `su - postgres -c "psql postgres -tAc \"SELECT 1 FROM pg_database WHERE datname='$db_name'\""`  == "1" ]]
-    then
-      echo "database $db_name exists"
-    else
-      su - postgres -c "createdb $db_name -O $db_admin -E UTF-8"
+      echo "remote database"
+
+      RET=
+      db_get xroad-common/database-password
+      master_passwd="$RET"
+      export PGPASSWORD=${master_passwd}
+
+      if  ! psql -h $db_addr -p $db_port -U postgres --list -tAF ' ' | grep template1 | awk '{print $3}' | grep -q "UTF8"
+       then echo -e "\n\npostgreSQL is not UTF8 compatible."
+          echo -e "Aborting installation! please fix issues and rerun with apt-get -f install\n\n"
+          exit 101
+      fi
+
+      if [[ `psql -h $db_addr -p $db_port -U postgres postgres -tAc "SELECT 1 FROM pg_roles WHERE rolname='${db_admin}'"` != "1" ]]
+      then
+          echo "CREATE ROLE $db_admin LOGIN PASSWORD '${db_admin_passwd}';" | psql -h $db_addr -p $db_port -U postgres postgres
+      fi
+
+      if [[ `psql -h $db_addr -p $db_port -U postgres postgres -tAc "SELECT 1 FROM pg_roles WHERE rolname='${db_user}'"` == "1" ]]
+       then
+          echo  "$db_user user exists, skipping role creation"
+          echo "ALTER ROLE ${db_user} WITH PASSWORD '${db_passwd}';" | psql -h $db_addr -p $db_port -U postgres postgres
+      else
+          echo "CREATE ROLE ${db_user} LOGIN PASSWORD '${db_passwd}';" | psql -h $db_addr -p $db_port -U postgres postgres
+      fi
+
+      if [[ `psql -h $db_addr -p $db_port -U postgres postgres -tAc "SELECT 1 FROM pg_database WHERE datname='${db_name}'"`  == "1" ]]
+      then
+          echo "database $db_name exists"
+      else
+          echo "GRANT ${db_user} to postgres" | psql -h $db_addr -p $db_port -U postgres postgres
+          echo "GRANT ${db_admin} to postgres" | psql -h $db_addr -p $db_port -U postgres postgres
+          createdb -h $db_addr -p $db_port -U postgres ${db_name} -O ${db_admin} -E UTF-8
+      fi
+
+      echo "ALTER ROLE ${db_admin} WITH PASSWORD '${db_admin_passwd}';" | psql -h $db_addr -p $db_port -U postgres postgres
+
+      echo "grant usage on schema public to ${db_user};" | psql -h $db_addr -p $db_port -U postgres postgres
+      echo "grant select, insert, update, delete on all tables in schema public to ${db_user};" | psql -h $db_addr -p $db_port -U postgres postgres
+      echo "grant usage, select, update on all sequences in schema public to ${db_user};" | psql -h $db_addr -p $db_port -U postgres postgres
+      echo "grant execute on all functions in schema public to ${db_user};" | psql -h $db_addr -p $db_port -U postgres postgres
+
     fi
 
     touch ${db_properties}
-
     crudini --set ${db_properties} '' op-monitor.hibernate.jdbc.use_streams_for_binary true
     crudini --set ${db_properties} '' op-monitor.hibernate.dialect ee.ria.xroad.common.db.CustomPostgreSQLDialect
     crudini --set ${db_properties} '' op-monitor.hibernate.connection.driver_class org.postgresql.Driver
@@ -77,21 +133,12 @@ else
 
 fi
 
-echo "ALTER ROLE ${db_admin} WITH PASSWORD '${db_admin_passwd}';" | su - postgres -c psql postgres
-
 chown xroad:xroad ${db_properties}
 chmod 640 ${db_properties}
 
 echo "running ${db_name} database migrations"
 cd /usr/share/xroad/db/
 /usr/share/xroad/db/liquibase.sh --classpath=/usr/share/xroad/jlib/postgresql.jar:/usr/share/xroad/jlib/common-db.jar --url="${db_url}?dialect=ee.ria.xroad.common.db.CustomPostgreSQLDialect" --changeLogFile=/usr/share/xroad/db/${db_name}-changelog.xml --password=${db_admin_passwd} --username=${db_admin} update || die "Connection to database has failed, please check database availability and configuration in ${db_properties} file"
-
-su - postgres -c "psql -d ${db_name}" << EOF
-grant usage on schema public to ${db_user};
-grant select, insert, update, delete on all tables in schema public to ${db_user};
-grant usage, select, update on all sequences in schema public to ${db_user};
-grant execute on all functions in schema public to ${db_user};
-EOF
 
 #DEBHELPER#
 
